"""A 684-word forbidden reduced base with two nonrelative sections.
Use the certified 683-word block expansion, one rank-three ample addition,
and the one-concept forbidden-extension theorem. No output minor search.
"""
from pathlib import Path
import hashlib,json,sys
HERE=Path(__file__).resolve().parent
sys.path.insert(0,str(HERE.parents[2]/'forbidden_pc_minor_campaign'))
from verify_damp_alternating_reductions import cube_shadow,columns,corner,directions

def main():
 src=HERE/'block_relative_transfer.json';r=json.loads(src.read_text());W=set(r['family']);V=W|{2167};g=range(13)
 assert 2167 not in W and len(V)==684
 support=sum(1<<q for q in directions(V,2167,g));assert support==265 and support.bit_count()==3
 sw=cube_shadow(W,g);sv=cube_shadow(V,g);assert sv-sw=={265}
 assert [v for v in sorted(V) if corner(V,v,g)]==[2167]
 assert min(len(directions(V,v,g)) for v in V)==3
 clauses,groups,_=columns(V,g,sv);assert groups==[[j] for j in g]
 # Recover from the output, without supplying its block pair or old word.
 a=next(v for v in V if corner(V,v,g));predecessor=V-{a}
 _,pre_groups,_=columns(predecessor,g)
 pairs=[pair for pair in pre_groups if len(pair)==2]
 assert pairs==[[11,12]] and ((a>>11)&1)!=((a>>12)&1)
 recovered={v&~(1<<12) for v in predecessor if not v&(1<<12) and v^(1<<12) in predecessor}
 assert recovered==set(r['negative_reduction']) and a&2047==119
 assert not any(corner(recovered,v,range(12)) for v in recovered)
 O=set(r['negative_reduction']);L=[{v&~(1<<12) for v in V if v>>12==b} for b in (0,1)]
 assert L[0]&L[1]==O
 assert [v for v in sorted(L[0]-O) if corner(L[0],v,range(12))]==[2167]
 assert not any(corner(L[0]-{2167},v,range(12)) for v in L[0]-O-{2167})
 assert not any(corner(L[1],v,range(12)) for v in L[1]-O)
 orders=[[2167]+r['section_orders'][0],r['section_orders'][1]]
 for F,order in zip(L,orders):
  left=set(F)
  for v in order:assert corner(left,v,range(12));left.remove(v)
  assert not left
 out=dict(recovered_block_pair=pairs[0],recovered_seed=sorted(recovered),recovered_old_word=a&2047,family=sorted(V),order=684,dimension=13,added_word=2167,old_row_word=119,acquired_support=265,unique_corner=2167,minimum_degree=3,signed_clauses=clauses,column_classes=groups,negative_overlap=sorted(O),positive_section_orders=orders,relative_failure='Zero section must delete 2167 and then has no permissible first deletion. One section has no permissible first deletion initially.',forbiddenness='Ample one-concept extension of the certified forbidden block expansion, with unchanged negative reduction. Apply the one-concept atlas theorem.',source_sha256=hashlib.sha256(src.read_bytes()).hexdigest(),scope='Reduced under graph-three-core and signed-column operations, but generated by the proved block plus nonconstant-row completion. Not a counterexample to all known generative operations.')
 Path(__file__).with_suffix('.json').write_text(json.dumps(out,indent=2)+'\n')
 print('PASS: 684 words; unique rank-three corner 2167; minimum degree 3; 13 distinct signed columns; negative overlap 267; both relative failures certified.')
if __name__=='__main__':main()
