#!/usr/bin/env python3
"""Generate database-owned LaTeX catalogue fragments."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


SECTIONS = ("class-table", "class-definitions", "bibliography")


def records(data_dir: Path, table: str) -> list[dict]:
    return [
        json.loads(path.read_text(encoding="utf-8"))
        for path in sorted((data_dir / table).glob("[0-9]*.json"))
    ]


def reference_key(reference: str) -> str:
    return reference.rsplit("/", 1)[-1]


def label_for(entry: dict, config: dict) -> str:
    return entry.get("latex_label") or config.get("label_overrides", {}).get(
        entry["short_name"],
        config["default_label_template"].format(short_name=entry["short_name"]),
    )


def _escape_plain(text: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(character, character) for character in text)


def latex_text(text: str) -> str:
    """Convert the catalogue's small Markdown/TeX subset to LaTeX."""
    pieces = re.split(r"(\$[^$]*\$|\\cite\w*\{[^}]+\}|\[@[A-Za-z0-9_:.+-]+\])", text)
    converted = []
    for piece in pieces:
        if piece.startswith("$") and piece.endswith("$"):
            converted.append(piece)
            continue
        if re.fullmatch(r"\\cite\w*\{[^}]+\}", piece):
            converted.append(piece)
            continue
        citation = re.fullmatch(r"\[@([A-Za-z0-9_:.+-]+)\]", piece)
        if citation:
            converted.append(r"\cite{" + citation.group(1) + "}")
            continue
        escaped = _escape_plain(piece)
        escaped = re.sub(r"\*\*([^*]+)\*\*", r"\\textbf{\1}", escaped)
        escaped = re.sub(r"`([^`]+)`", r"\\texttt{\1}", escaped)
        converted.append(escaped)
    return "".join(converted)


def generated_header(section: str) -> list[str]:
    return [
        "% GENERATED by Partial-Cubes/sync/generate_latex_catalog.py; do not edit.",
        f"% Section: {section}",
        "",
    ]


def generate_class_table(data_dir: Path, mapping: dict) -> str:
    lines = generated_header("class-table")
    lines.extend([
        r"\begin{longtable}{@{}lllll@{}}",
        r"\textbf{Class} & \textbf{Symbol} & \textbf{P} & \textbf{C} & \textbf{PC} \\",
        r"\hline",
        r"\endhead",
    ])
    for entry in records(data_dir, "classes"):
        label = label_for(entry, mapping["classes"])
        symbol = f'${entry["symbol"]}$' if entry.get("symbol") else ""
        marker = lambda field: "Yes" if entry.get(field) is True else "No" if entry.get(field) is False else "?"
        lines.append(
            rf"\hyperref[{label}]{{{latex_text(entry['name'])}}} & {symbol} & "
            rf"{marker('p_closed')} & {marker('c_closed')} & {marker('pc_closed')} \\"
        )
    lines.extend([r"\end{longtable}", ""])
    return "\n".join(lines)


def generate_class_definitions(data_dir: Path, mapping: dict) -> str:
    lines = generated_header("class-definitions")
    classes = records(data_dir, "classes")
    characterizations = records(data_dir, "characterizations")
    class_aliases = {
        alias: entry["short_name"]
        for entry in classes
        for alias in (entry["short_name"], str(entry["id"]))
    }
    characterization_aliases = {
        alias: entry["short_name"]
        for entry in characterizations
        for alias in (entry["short_name"], str(entry["id"]))
    }
    by_class: dict[str, list[dict]] = {}
    for characterization in characterizations:
        class_key = reference_key(characterization["class_id"])
        by_class.setdefault(class_aliases.get(class_key, class_key), []).append(characterization)

    for entry in classes:
        class_label = label_for(entry, mapping["classes"])
        primary_reference = reference_key(entry["primary_characterization_id"])
        primary_key = characterization_aliases.get(primary_reference, primary_reference)
        criteria = sorted(
            by_class.get(entry["short_name"], []),
            key=lambda item: (item["short_name"] != primary_key, item["id"]),
        )
        lines.extend([
            rf"\subsection{{{latex_text(entry['name'])}}}",
            rf"\label{{{class_label}}}",
            latex_text(entry["summary"]),
            "",
        ])
        for criterion in criteria:
            criterion_label = label_for(criterion, mapping["characterizations"])
            heading = "Primary characterization" if criterion["short_name"] == primary_key else criterion["name"]
            lines.extend([
                rf"\paragraph{{{latex_text(heading)}.}}",
                rf"\label{{{criterion_label}}}",
                latex_text(criterion["statement"]),
            ])
            if criterion.get("hypotheses"):
                lines.append(r"\emph{Hypotheses.} " + latex_text(criterion["hypotheses"]))
            if criterion.get("status") != "established":
                lines.append(r"\emph{Status.} " + latex_text(criterion["status"].replace("_", " ").title()) + ".")
            if criterion.get("references"):
                lines.append(r"\emph{References.} " + latex_text(criterion["references"]))
            lines.append("")
    return "\n".join(lines)


def generate_bibliography(data_dir: Path, _mapping: dict) -> str:
    bibliography = (data_dir / "latex" / "references.bib").read_text(encoding="utf-8")
    return "\n".join(generated_header("bibliography")) + bibliography.rstrip() + "\n"


GENERATORS = {
    "class-table": generate_class_table,
    "class-definitions": generate_class_definitions,
    "bibliography": generate_bibliography,
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-dir", type=Path, default=Path("data"))
    parser.add_argument("--mapping", type=Path, default=Path(__file__).with_name("latex_mapping.json"))
    parser.add_argument("--section", choices=SECTIONS, required=True)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    data_dir = args.data_dir.resolve()
    mapping = json.loads(args.mapping.read_text(encoding="utf-8"))
    content = GENERATORS[args.section](data_dir, mapping)
    if not args.output:
        if args.check:
            parser.error("--check requires --output")
        sys.stdout.write(content)
        return 0

    output = args.output.expanduser().resolve()
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != content:
            print(f"Generated LaTeX is out of date: {output}", file=sys.stderr)
            return 1
        print(f"Generated LaTeX is current: {output}")
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")
    print(f"Wrote {args.section} to {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
